// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqf7s_aAwhr_KfS0ufy4P9OYKneLCykI',
    appId: '1:972796679781:web:12fe5d02f5a410fbb5588c',
    messagingSenderId: '972796679781',
    projectId: 'psychoai-143a7',
    authDomain: 'psychoai-143a7.firebaseapp.com',
    storageBucket: 'psychoai-143a7.appspot.com',
    measurementId: 'G-M7K4RETNPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IYAurppuRsrzxpnuQGFFCvUO_dnQ4cs',
    appId: '1:972796679781:android:ac027f83775a2bc9b5588c',
    messagingSenderId: '972796679781',
    projectId: 'psychoai-143a7',
    storageBucket: 'psychoai-143a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7L2KacamPuKzCM7NOkRuxGuD7r8wI1KU',
    appId: '1:972796679781:ios:762dd43c9dbc7ddfb5588c',
    messagingSenderId: '972796679781',
    projectId: 'psychoai-143a7',
    storageBucket: 'psychoai-143a7.appspot.com',
    iosBundleId: 'com.example.psychoai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7L2KacamPuKzCM7NOkRuxGuD7r8wI1KU',
    appId: '1:972796679781:ios:762dd43c9dbc7ddfb5588c',
    messagingSenderId: '972796679781',
    projectId: 'psychoai-143a7',
    storageBucket: 'psychoai-143a7.appspot.com',
    iosBundleId: 'com.example.psychoai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqf7s_aAwhr_KfS0ufy4P9OYKneLCykI',
    appId: '1:972796679781:web:30d75090c84816b5b5588c',
    messagingSenderId: '972796679781',
    projectId: 'psychoai-143a7',
    authDomain: 'psychoai-143a7.firebaseapp.com',
    storageBucket: 'psychoai-143a7.appspot.com',
    measurementId: 'G-8Q88BR4GNX',
  );
}
